// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtRETR-6uk_MWppaYn5ZU5IwfqzfxGAC4',
    appId: '1:61222074778:android:1b4e0514fb8effeb4c6223',
    messagingSenderId: '61222074778',
    projectId: 'flutter-chat-app-e13af',
    storageBucket: 'flutter-chat-app-e13af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5e58r1wXSUYWCaJsT1Pp4nNy3kdR4R70',
    appId: '1:61222074778:ios:3e588101977c1a754c6223',
    messagingSenderId: '61222074778',
    projectId: 'flutter-chat-app-e13af',
    storageBucket: 'flutter-chat-app-e13af.firebasestorage.app',
    iosBundleId: 'com.example.eightApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLCbvE69Ki3Y2w7xgIMHpATWkhwVYw3X8',
    appId: '1:61222074778:web:54c80ed5c190b67c4c6223',
    messagingSenderId: '61222074778',
    projectId: 'flutter-chat-app-e13af',
    authDomain: 'flutter-chat-app-e13af.firebaseapp.com',
    storageBucket: 'flutter-chat-app-e13af.firebasestorage.app',
    measurementId: 'G-XY7D2G60Y4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5e58r1wXSUYWCaJsT1Pp4nNy3kdR4R70',
    appId: '1:61222074778:ios:3e588101977c1a754c6223',
    messagingSenderId: '61222074778',
    projectId: 'flutter-chat-app-e13af',
    storageBucket: 'flutter-chat-app-e13af.firebasestorage.app',
    iosBundleId: 'com.example.eightApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLCbvE69Ki3Y2w7xgIMHpATWkhwVYw3X8',
    appId: '1:61222074778:web:3ce08772ba22d23d4c6223',
    messagingSenderId: '61222074778',
    projectId: 'flutter-chat-app-e13af',
    authDomain: 'flutter-chat-app-e13af.firebaseapp.com',
    storageBucket: 'flutter-chat-app-e13af.firebasestorage.app',
    measurementId: 'G-TP7CG85C52',
  );

}